backend:
  vault_token: aHZzLkNBRVNJRmkwVC1lUldlN2ozQ0lkc0poSDZPdzVmSTA0X0FJbEZxU2pYUXk0Z1Q2UUdoNEtIR2gyY3k1bWNrSk5Vbm8xTkRkTmNHaE9ibFJWUlVwcVptTm5aRUU=
  vault_host: 62.84.114.149

  vpa:
    updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 0
            memory: 0Mi
          maxAllowed:
            cpu: 1
            memory: 1024Mi
          controlledResources: ["cpu", "memory"]
          controlledValues: RequestsAndLimits

  replicaCount: 2
  revisionHistoryLimit: 15

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%

  image:
    repository: gitlab.praktikum-services.ru:5050/a.voronin/sausage-store/sausage-backend
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: [{ name: docker-config-secret}]
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}


  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false

  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

backend-report:
  spring_data_mongodb_uri: bW9uZ29kYjovL3ZvcmFsZXhhbjpUZXN0dXNyMTIzNEByYzFiLWk1MDFrOXJ1enVib3ZiMngubWRiLnlhbmRleGNsb3VkLm5ldDoyNzAxOC92b3JhbGV4YW4/dGxzPXRydWUmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWU=

  replicaCount: 1
  revisionHistoryLimit: 15

  image:
    repository:  gitlab.praktikum-services.ru:5050/a.voronin/sausage-store/sausage-backend-report
    pullPolicy: Always
    tag: "latest"

  imagePullSecrets: [{ name: docker-config-secret}]
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  resources: {}

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75


  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

frontend:
  # Default values for frontend.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  replicaCount: 1
  revisionHistoryLimit: 15
  image:
    repository: gitlab.praktikum-services.ru:5050/a.voronin/sausage-store/sausage-frontend
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: [{ name: docker-config-secret}]
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}


  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: "voronin-aleksey-12.k8s.praktikum-services.tech"
        paths:
          - path: /
            pathType: Prefix
    tls: [hosts: ["voronin-aleksey-12.k8s.praktikum-services.tech"]]
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi


  nodeSelector: {app: "frontend"}

  tolerations: []

  affinity: {}
