---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-report.fullname" . }}-mongo
  labels:
    {{- include "backend-report.labels" . | nindent 4 }}
data:
  spring_data_mongodb_uri:  {{ .Values.spring_data_mongodb_uri }}
type: Opaque