---
- name: Update apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  become: true

- name: Install packages
  apt:
    pkg:
    - npm
  become: true


- name: Install nodejs
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs
  become: true

- name: Add service account
  user:
    name: "{{ frontend_service_user }}"
    create_home: no
    shell: /sbin/nologin
  become: true

- name: Create directory for frontend files
  file:
    path: "{{ frontend_lib_directory }}"
    state: directory
    group: "{{ frontend_service_user }}"
    owner: "{{ frontend_service_user }}"
    recurse: true
    mode: 0755
  become: true

- name: Download Nexus tgz
  get_url:
    username: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    url: "https://nexus.praktikum-services.ru/repository/sausage-store-voronin-aleksey-frontend/{{ frontend_version }}/sausage-store-{{ frontend_version }}.tar.gz"
    dest: "{{ frontend_lib_directory }}"
    mode: '0440'
  become: true

- name: Extract frontend files
  unarchive:
    src: "{{ frontend_lib_directory }}/sausage-store-{{ frontend_version }}.tar.gz"
    dest: "{{ frontend_lib_directory }}"
    remote_src: yes
  become: true

- name: Create service
  template:
    src: sausage-store-frontend.service.j2
    dest: /etc/systemd/system/sausage-store-frontend.service
  become: true

- name: sudo without password for www-data group
  copy:
    content: '%{{ frontend_service_user }} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/front_nopasswd
    mode: 0440
  become: true

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: Start frontend
  service:
    name: sausage-store-frontend
    state: started
  become: true