create table IF NOT EXISTS  order_product
(
    quantity integer not null,
    order_id bigint not null,
    product_id bigint not null

);

create table IF NOT EXISTS orders
(
    id bigint generated by default as identity,
    date_created date,
    status varchar(255)
);

create table IF NOT EXISTS product
(
    id bigint generated by default as identity,
    name varchar(255) not null,
    picture_url varchar(255),
    price double precision
);