spring_data_mongodb_uri:  bW9uZ29kYjovL3ZvcmFsZXhhbjpUZXN0dXNyMTIzNEByYzFiLWk1MDFrOXJ1enVib3ZiMngubWRiLnlhbmRleGNsb3VkLm5ldDoyNzAxOC92b3JhbGV4YW4/dGxzPXRydWUmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWU=

replicaCount: 1
revisionHistoryLimit: 15

image:
  repository:  gitlab.praktikum-services.ru:5050/a.voronin/sausage-store/sausage-backend-report
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: [docker-config-secret]
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75


resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
