---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: backend
data:
  vault_token: aHZzLkNBRVNJRmkwVC1lUldlN2ozQ0lkc0poSDZPdzVmSTA0X0FJbEZxU2pYUXk0Z1Q2UUdoNEtIR2gyY3k1bWNrSk5Vbm8xTkRkTmNHaE9ibFJWUlVwcVptTm5aRUU=
type: Opaque