---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-vault
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  vault_token: {{ .Values.vault_token }}
type: Opaque