variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - module-pipelines
  - compose

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/cicd/frontend-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/cicd/backend-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

backend-report:
  stage: module-pipelines
  trigger:
    include:
      - "/cicd/backend-report-ci.yml"
    strategy: depend
  only:
    changes:
      - backend-report/**/*

docker-compose:
  stage: compose
  when: manual
  image: alpine:3.15.0
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -r ./frontend  ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/
    - scp -r ./backend  ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/
    - scp -r ./backend-report  ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/
    - scp ./docker-compose.yml ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/docker-compose.yml
    - ssh ${DEV_USER}@${DEV_HOST}
      "export "SPRING_DATASOURCE_URL=${PSQL_DATASOURCE}";
       export "SPRING_DATASOURCE_USERNAME=${PSQL_USER}";
       export "SPRING_DATASOURCE_PASSWORD=${PSQL_PASSWORD}";
       export "SPRING_DATA_MONGODB_URI=${MONGO_DATA}";
       envsubst < docker-compose.yml;
       docker-compose up -d --force-recreate"