---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  labels:
    app: backend-report
data:
  spring_data_mongodb_uri: bW9uZ29kYjovL3ZvcmFsZXhhbjpUZXN0dXNyMTIzNEByYzFiLWk1MDFrOXJ1enVib3ZiMngubWRiLnlhbmRleGNsb3VkLm5ldDoyNzAxOC92b3JhbGV4YW4/dGxzPXRydWUmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWU=
type: Opaque